apiVersion: v1
kind: Service
metadata:
  name: custom-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: custom
  ports:
  - port: 80
    targetPort: 80

# One of other attempts to expose the service; doesn't work