apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment
spec:
  selector:
    matchLabels:
      app: custom
  replicas: 1 
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: ilyassakhanov/btc-app:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: custom-deployment-service
spec:
  selector:
    app: custom
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000